server:
  port: 8083

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&tinyInt1isBit=true
#    username: root
#    password: admin

#  p6spy配置
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&tinyInt1isBit=true
    username: root
    password: admin


  profiles:
      active: prod
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml

# pagehelper
pagehelper :
  helperDialect: Mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql